[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/exercisedb/*"
  to = "/.netlify/functions/exercisedb/:splat"
  status = 200
